version: '3'

services:
  front-web:
    build: 
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - '../../code:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: ["yarn", "run", "dev"]