version: '3.5'

services:
  front-web:
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - '../..:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ESLINT_NO_DEV_ERRORS=true
      - REACT_APP_FIREBASE_KEY=${FIREBASE_KEY}
      - REACT_APP_FIREBASE_DOMAIN=${FIREBASE_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_SENDER_ID=${FIREBASE_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - REACT_APP_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - REACT_APP_API_URL=${API_URL:-http://localhost:8081/v2/graphql}
    stdin_open: true
